# Only run on Linux machines
agents:
  queue: "julia"
  os: "linux"

steps:
  - label: ":julia: Julia v1"
    plugins:
      # Use `metahook` to modify the Project.toml to have a different UUID for testing
      - improbable-eng/metahook:
          post-checkout: |
            sed -i'' -e 's/ea8e919c-243c-51af-8825-aaa63cd721ce/ea8e919c-243c-51af-8825-aaa63cd721cf/' Project.toml
      - JuliaCI/julia#v1:
          version: "1"
      - JuliaCI/julia-test#v1: ~
      - JuliaCI/julia-coverage#v1:
          codecov: true

  - label: ":julia: Julia nightly"
    plugins:
      # Use `metahook` to modify the Project.toml to have a different UUID for testing
      - improbable-eng/metahook:
          post-checkout: |
            sed -i'' -e 's/ea8e919c-243c-51af-8825-aaa63cd721ce/ea8e919c-243c-51af-8825-aaa63cd721cf/' Project.toml
      - JuliaCI/julia#v1:
          version: "nightly"
      - JuliaCI/julia-test#v1: ~
      - JuliaCI/julia-coverage#v1:
          codecov: true
