name: CI
on:
  pull_request:
    branches:
      - "master"
  push:
    branches:
      - "master"
    tags:
      - "*"
defaults:
  run:
    shell: bash
jobs:
  test:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-latest
          - ubuntu-latest
          - macos-latest
        julia-version:
          - "1.6"
          - "1"
          - "nightly"
        exclude:
          - os: macos-latest
            julia-version: nightly
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
      - uses: julia-actions/setup-julia@v1
        with:
          show-versioninfo: true
          version: ${{ matrix.julia-version }}
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v2
        with:
          file: lcov.info
  doctest:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      matrix:
        os:
          - ubuntu-latest
        julia-version:
          - "1"
          - "nightly"
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
      - uses: julia-actions/setup-julia@v1
        with:
          show-versioninfo: true
          version: ${{ matrix.julia-version }}
      - run: julia --project=docs --color=yes -e 'using Pkg; Pkg.instantiate()'
      - run: julia --project=docs --color=yes -e 'using Pkg; Pkg.develop(PackageSpec(path = pwd()))'
      - run: julia --project=docs --color=yes -e 'using Documenter, SHA3; doctest(SHA3)'
